# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeedDetails',
            fields=[
                ('need_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_id', models.IntegerField()),
                ('need_type', models.IntegerField()),
                ('is_satisfied', models.BooleanField(default=False)),
                ('main_item_id', models.IntegerField()),
                ('need_txt_desc', models.CharField(max_length=500)),
            ],
        ),
    ]
