# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Humane', '0003_auto_20170718_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleLookUp',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_role_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='AllowedUnitLookUp',
        ),
        migrations.DeleteModel(
            name='CoordinatorDetail',
        ),
        migrations.DeleteModel(
            name='DonationDetail',
        ),
        migrations.DeleteModel(
            name='DonationItemDetail',
        ),
        migrations.DeleteModel(
            name='GoodsDetail',
        ),
        migrations.DeleteModel(
            name='GoodsItemDetail',
        ),
        migrations.DeleteModel(
            name='MainItemTypeLookUp',
        ),
        migrations.DeleteModel(
            name='RequestTypeLookUp',
        ),
        migrations.DeleteModel(
            name='SubItemTypeLookUp',
        ),
        migrations.DeleteModel(
            name='UnitLookUp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='region_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='registered_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Humane.UserRoleLookUp'),
            preserve_default=False,
        ),
    ]
