# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 12:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Humane', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(null=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Latitude should be in proper format', regex='^[0-9]*(\\.\\d{1,4})?$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(null=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Longitude should be in proper format', regex='^[0-9]*(\\.\\d{1,4})?$')]),
        ),
    ]
