# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Humane', '0002_auto_20170720_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedUnitLookUp',
            fields=[
                ('allowed_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_item_id', models.IntegerField()),
                ('unit_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('goods_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_id', models.IntegerField()),
                ('request_type', models.IntegerField()),
                ('is_satisfied', models.BooleanField(default=False)),
                ('main_item_id', models.IntegerField()),
                ('goods_txt_desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsItemDetail',
            fields=[
                ('goods_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('posted_date', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('sub_item_id', models.IntegerField()),
                ('unit_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MainItemTypeLookUp',
            fields=[
                ('main_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_item_name', models.CharField(max_length=100)),
                ('request_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestTypeLookUp',
            fields=[
                ('request_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('rquest_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubItemTypeLookUp',
            fields=[
                ('sub_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_item_name', models.CharField(max_length=100)),
                ('main_item_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UnitLookUp',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=100)),
            ],
        ),
    ]
