# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Humane', '0005_auto_20170728_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainitemtypelookup',
            name='request_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Humane.RequestTypeLookUp'),
        ),
    ]
