# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Humane', '0006_auto_20170728_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsdetail',
            name='org_name',
        ),
        migrations.AddField(
            model_name='goodsdetail',
            name='org_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Humane.OrganisationDetail'),
            preserve_default=False,
        ),
    ]
