# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 14:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Humane', '0010_donationdetail_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoantingUserDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=25)),
                ('latitude', models.FloatField(null=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Latitude should be in proper format', regex='^[0-9]*(\\.\\d{1,4})?$')])),
                ('longitude', models.FloatField(null=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Latitude should be in proper format', regex='^[0-9]*(\\.\\d{1,4})?$')])),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='donationdetail',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_list', to='Humane.GoodsDetail'),
        ),
        migrations.AlterField(
            model_name='donationitemdetail',
            name='donation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_item_list', to='Humane.DonationDetail'),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_detail', to='Humane.OrganisationDetail'),
        ),
        migrations.AddField(
            model_name='doantinguserdetail',
            name='donation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Humane.DonationDetail'),
        ),
    ]
