# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Humane', '0011_auto_20170729_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationitemdetail',
            name='goods_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_item_list', to='Humane.GoodsItemDetail'),
        ),
    ]
