# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Humane', '0012_auto_20170729_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsdetail',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_details', to='Humane.OrganisationDetail'),
        ),
    ]
