# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Humane', '0013_auto_20170729_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationitemdetail',
            name='goods_id',
        ),
        migrations.AddField(
            model_name='donationdetail',
            name='is_donation_completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
