# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Humane', '0015_auto_20170730_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationdetail',
            old_name='received_date',
            new_name='delivered_date',
        ),
    ]
