# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Humane', '0018_auto_20170730_0135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoantingUserDetail',
            new_name='DonatingUserDetail',
        ),
        migrations.RenameModel(
            old_name='CoordinatorDetail',
            new_name='OrganisationUserDetail',
        ),
    ]
