# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Humane', '0020_auto_20170731_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsitemdetail',
            name='goods_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Humane.GoodsDetail'),
        ),
    ]
