# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Humane', '0021_auto_20170731_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsitemdetail',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_item_list', to='Humane.GoodsDetail'),
        ),
    ]
