# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 12:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Humane', '0025_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedunitlookup',
            name='sub_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Humane.SubItemTypeLookUp'),
        ),
        migrations.AlterField(
            model_name='allowedunitlookup',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Humane.UnitLookUp'),
        ),
        migrations.AlterField(
            model_name='donationdetail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationitemdetail',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Humane.UnitLookUp'),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='main_item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Humane.MainItemTypeLookUp'),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Humane.RequestTypeLookUp'),
        ),
        migrations.AlterField(
            model_name='goodsitemdetail',
            name='sub_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Humane.SubItemTypeLookUp'),
        ),
        migrations.AlterField(
            model_name='goodsitemdetail',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Humane.UnitLookUp'),
        ),
        migrations.AlterField(
            model_name='mainitemtypelookup',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Humane.RequestTypeLookUp'),
        ),
        migrations.AlterField(
            model_name='organisationdetail',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='organisationdetail',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='organisationuserdetail',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Humane.OrganisationDetail'),
        ),
        migrations.AlterField(
            model_name='organisationuserdetail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subitemtypelookup',
            name='main_item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Humane.MainItemTypeLookUp'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Humane.UserRoleLookUp'),
        ),
    ]
