# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Humane', '0026_auto_20170731_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsitemdetail',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
