# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Humane', '0028_auto_20170731_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationdetail',
            name='delivered_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='donationdetail',
            name='is_donation_completed',
            field=models.BooleanField(default=False),
        ),
    ]
