# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-01 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Humane', '0033_auto_20170801_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationdetail',
            name='org_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
