# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Humane', '0036_auto_20170801_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatinguserdetail',
            name='donation_id',
        ),
        migrations.AlterField(
            model_name='donationdetail',
            name='is_volunteer_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donationitemdetail',
            name='delivered_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='goods_txt_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='organisationdetail',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisationdetail',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisationdetail',
            name='org_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DonatingUserDetail',
        ),
    ]
