# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Humane', '0039_auto_20170802_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowedunitlookup',
            old_name='sub_item_id',
            new_name='sub_item',
        ),
        migrations.RenameField(
            model_name='allowedunitlookup',
            old_name='unit_id',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='donationdetail',
            old_name='goods_id',
            new_name='goods',
        ),
        migrations.RenameField(
            model_name='donationdetail',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='donationitemdetail',
            old_name='donation_id',
            new_name='donation',
        ),
        migrations.RenameField(
            model_name='donationitemdetail',
            old_name='goods_id',
            new_name='goods',
        ),
        migrations.RenameField(
            model_name='donationitemdetail',
            old_name='goods_item_id',
            new_name='goods_item',
        ),
        migrations.RenameField(
            model_name='donationitemdetail',
            old_name='unit_id',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='goodsdetail',
            old_name='main_item_name',
            new_name='main_item',
        ),
        migrations.RenameField(
            model_name='goodsdetail',
            old_name='org_id',
            new_name='organisation',
        ),
        migrations.RenameField(
            model_name='goodsdetail',
            old_name='request_type',
            new_name='request',
        ),
        migrations.RenameField(
            model_name='goodsitemdetail',
            old_name='goods_id',
            new_name='goods',
        ),
        migrations.RenameField(
            model_name='goodsitemdetail',
            old_name='sub_item_id',
            new_name='sub_item',
        ),
        migrations.RenameField(
            model_name='goodsitemdetail',
            old_name='unit_id',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='mainitemtypelookup',
            old_name='request_type',
            new_name='request',
        ),
        migrations.RenameField(
            model_name='organisationuserdetail',
            old_name='org_id',
            new_name='organisation',
        ),
        migrations.RenameField(
            model_name='organisationuserdetail',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subitemtypelookup',
            old_name='main_item_name',
            new_name='main_item',
        ),
    ]
