# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Humane', '0040_auto_20170803_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationdetail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
